# Generated by Django 4.1.3 on 2022-12-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dob',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='gender',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
